language: csharp
solution: FailMail.sln
install:
  - nuget restore FailMail.sln
  - nuget install xunit.runners -Version 2.1.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release FailMail.sln
  - mono ./testrunner/xunit.runners.2.1.0/tools/xunit.console ./FailMail.Tests/bin/Release/FailMail.Tests.dll